### ISSUE TITLE
Example doesn't work with stock SDK 13.0.0

### ISSUE THREAD

**Issue by labishrestha** [NordicSemiconductor/nrf528xx-ble-throughput-demo#1]
Not sure exactly how to get this working on stock SDK 13.0.0 seems like some configuration regarding NRF_LOG is missing, even after adding that, I still couldn't get it working. 

```
/usr/bin/make -f Makefile
Makefile:235: Cannot find source file:  ../../../../../../../components/libraries/util/sdk_errors.c
Makefile:235: Cannot find include folder:  ../../../../../../../components/drivers_nrf/adc
Compiling file: nrf_log_backend_serial.c
Compiling file: nrf_log_frontend.c
In file included from ../../../../../../../components/libraries/log/src/nrf_log_frontend.c:44:0:
../../../../../../../components/libraries/log/nrf_log.h:54:26: fatal error: nrf_strerror.h: No such file or directory
 #include "nrf_strerror.h"
```

**Comment by haakonsh** [comment]
It's a bug in README. It should say [nRF5_SDK_13.0.0-1.alpha](http://developer.nordicsemi.com/nRF5_SDK/nRF5_SDK_v13.x.x/nRF5_SDK_13.0.0-1.alpha_055eef3.zip)

-edit
Fixed
